### ISSUE TITLE
Todo: Publish

### ISSUE THREAD

**Issue by ThomasLeister** [aditosoftware/nodepki#4]
- [ ]  Review source code, remove unnecessary comments and make code nice
- [x]  Finish README (Installation and usage)
- [x]  Check installation instructions
- [x]  Build and publish Docker image
